### PR TITLE
Use zotero-plugin-scaffold instead of zotero-plugin-template scripts

### LINKED ISSUE #272: Use zotero-plugin-scaffold?
Hey, @Dominic-DallOsto! So I finally managed to install Node 18 on my computer, so I'm now ready to start trying what you've doing to support Zotero 7 (#257).

First thing I came up with when trying `npm start` is an error because my Zotero profile doesn't have an `extensions` folder yet.

Of course this could be fixed by manually adding that folder, but apparently it was already fixed in `zotero-plugin-template`: https://github.com/windingwind/zotero-plugin-template/pull/113

Which made me think of: how can we benefit from this and future upgrades to zotero-plugin-template?

I'm just beginning to understand how this `zotero-plugin-template` works, but it looks to me that they may have recently moved (note the `zotero-plugin-scaffold` requirement in their [`package.json`](https://github.com/windingwind/zotero-plugin-template/blob/main/package.json) file) the `build`, `serve`, etc scripts to a separate repo made exactly for that: "so that downstream developers can follow along". https://github.com/northword/zotero-plugin-scaffold

Do you think it may make sense to use this zotero-plugin-scaffold package too?

### PR DESCRIPTION
**Pull request by Dominic-DallOsto**
Fixes #272

### CODE REVIEW

**Comment by Dominic-DallOsto** [comment]
`npm run start` seems to also launch firefox debugging tools automatically - maybe we need to update the instructions to remove the part about manually downloading the firefox debug tools?

**Comment by diegodlh** [comment]
I've just checked this and it seems to be working for me too.

It just doesn't seem to be launching the Firefox debugging tools for me, though. Or maybe I did not understand what you meant by that. I expected Firefox to launch or something. What did you get?

**Comment by Dominic-DallOsto** [comment]
I run `npm run start` which launches Zotero.

```bash
➜ npm run start

> zotero-cita@0.6.0 start
> zotero-plugin serve

◐ Building version 0.6.0 to build at 2024-07-17 17:25:33 in development mode.     
ℹ Preparing manifest                     
ℹ Preparing locale files                            
ℹ Replacing                                                 
ℹ Running esbuild                          
ℹ Addon prepare OK.                        
✔ Build finished in 5.876 s.               

✔ Server Ready!
```

First I see this popup (might not happen if you built Zotero from source)

image

Then the "Parent process Browser Toolbox" is also opened

image

**Comment by diegodlh** [comment]
Regarding the Firefox debugging tools launching automatically...

I'm not getting neither the popup nor the "Parent process Browser Toolbox" window when running `npm start`. Don't know why.

I do get the window to open automatically (not the popup) if I run Zotero directly with `zotero -ZoteroDebugText -jsconsole -debugger`.

Anyways, I can get the window to open manually via `Tools > Developer > Error Console`.

Either way, I don't seem to be able to see the source files and set breakpoints this way; only the console. To do so I still need to use Firefox debugging tools from the browser. Is this your case too?

**Comment by diegodlh** [comment]
On the other hand, I just made a commit changing the `zotero-plugin.config.ts` file to create sourcemap files. This should greatly assist in debugging from the browser, as this way the original source files (instead of the output from the build process) are shown. @Dominic-DallOsto does this work for you too?

I wonder whether there is a way to just include these sourcemap files when building in `development` mode (when I run `npm start` it says `Building ... in development mode`). I'm sure there is! I just didn't look into it :)

**Comment by diegodlh** [comment]
Sorry, one more (very minor!) thing. I still find it a little confusing that we have renamed the `static` folder as `addon`. Because I think it doesn't express clearly that there are static assets inside.

Now that where assets are stored seems to be easily configured in `zotero-plugin.config.ts`... would you mind if I rename this back to `static` (or `assets`, if you prefer)?

**Comment by Dominic-DallOsto** [comment]
> Regarding the Firefox debugging tools launching automatically...
> 
> I'm not getting neither the popup nor the "Parent process Browser Toolbox" window when running `npm start`. Don't know why.
> 
> I do get the window to open automatically (not the popup) if I run Zotero directly with `zotero -ZoteroDebugText -jsconsole -debugger`.
> 
> Anyways, I can get the window to open manually via `Tools > Developer > Error Console`.
> 
> Either way, I don't seem to be able to see the source files and set breakpoints this way; only the console. To do so I still need to use Firefox debugging tools from the browser. Is this your case too?

Hmmm. Maybe it's a linux vs windows issue.

Do you get the debug tools if you run `zotero -jsdebugger`? What about if you run `zotero --jsdebugger`? I think this is a newly added flag that launches the full debugging tools with Zotero. Maybe firefox expects the argument with one dash, but zotero-plugin-scaffold uses 2, which maybe magically works on windows but not linux?

But how you describe with manually opening the error console, or launching the firefox debug tools from the browser to be able to set breakpoints, is what I used to have to do before switching to zotero-plugin-scaffold

**Comment by Dominic-DallOsto** [comment]
> On the other hand, I just made a commit changing the `zotero-plugin.config.ts` file to create sourcemap files. This should greatly assist in debugging from the browser, as this way the original source files (instead of the output from the build process) are shown. @Dominic-DallOsto does this work for you too?
> 
> I wonder whether there is a way to just include these sourcemap files when building in `development` mode (when I run `npm start` it says `Building ... in development mode`). I'm sure there is! I just didn't look into it :)

Apparently the "development" shown there is the Node environment [see here](https://nodejs.org/en/learn/getting-started/nodejs-the-difference-between-development-and-production).

There's also the option for whether we're building a beta or normal build which changes which update.json gets used.

But yeah I can just enable the sure maps in development mode.

**Comment by Dominic-DallOsto** [comment]
> Sorry, one more (very minor!) thing. I still find it a little confusing that we have renamed the `static` folder as `addon`. Because I think it doesn't express clearly that there are static assets inside.
> 
> Now that where assets are stored seems to be easily configured in `zotero-plugin.config.ts`... would you mind if I rename this back to `static` (or `assets`, if you prefer)?

I tried this and it doesn't work at the moment - the code at some point still assumes the static files are in a directory called addon. But I'll open an issue to fix that.

**Pull request merged**
