### PR TITLE
Add citations by identifier

### PR DESCRIPTION
**Pull request by Dominic-DallOsto**
Add an option to the dropdown menu to add citations by identifier (addressing #111). 

- [x] Basic support
- [x] Show progress / error handling
- [x] Support translation
- [x] Textbox for input

### CODE REVIEW

**Comment by diegodlh** [comment]
Thank you!! I'm trying to push some changes to the Dominic-DallOsto/issue111 branch on Dominic-DallOsto/zotero-cita, but I'm getting a "permission denied". This is my first time doing this, so I may be doing something wrong. But, just in case, could you please check that "allowing edits from maintainers" is [enabled](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

Thanks!

**Comment by diegodlh** [comment]
Thanks! Just pushed a commit with some changes.

Do you think you could add a textbox to input/paste and edit identifiers instead of directly getting them from the clipboard? I think it would be more transparent.

**Comment by Dominic-DallOsto** [comment]
I think this should be OK now. Note that at the moment (or at least until https://github.com/zotero/zotero/pull/1924 is merged), only one type of identifier can be imported at once.

**Review by diegodlh — COMMENTED** [review]
Great! I'll push some minor changes and merge now.

**Review by diegodlh — APPROVED** [review]

**Pull request merged**
