### PR TITLE
Remove base type `work` from untyped reconciliation query

### LINKED ISSUE #149: Fetching QIDs failed
When I try to fetch QID for a zotero article with DOI 10.1038/370386A0, which should return Q42598957, cita says "Fetching QIDs ..." for several minutes, then returns the error message: "Fetching QIDs failed". I'm running

macOS Catalina 10.15.7
Zotero 5.0.96.3
cita 0.3.2

I tried with several other articles with the same result. Any help would be much appreciated! Thanks!

### PR DESCRIPTION
**Pull request by Dominic-DallOsto**
Fixes #149

More of a hack than a proper fix but at least it gets things working again. I'm not sure `creative_work` covers all the types we care about?

As a further change - could we send the typed query first, then only send the untyped query if the typed one doesn't return anything?

### CODE REVIEW

**Comment by diegodlh** [comment]
> I'm not sure creative_work covers all the types we care about?

For the typed query, `wikidata.js`'s `reconcile` function uses a Zotero item type &rarr; QID map. This map is derived from Zotero's QuickStatements translator. Maybe we could [run a SPARQL query in Wikidata](https://query.wikidata.org/) to identify the most specific ancestor (i.e., parent class) for all QIDs in the map. If it is `creative_work` or something more specific, I think we should be OK with using `creative_work`. What do you think?

> could we send the typed query first, then only send the untyped query if the typed one doesn't return anything?

Probably this was the original idea, as described [here](https://github.com/diegodlh/zotero-cita/issues/101#issuecomment-864176874). I must have included both in the same request to minimize the number of requests. It should be OK to split them and only make a second untyped request for any query which returned zero **exact** matches for the typed request.

**Comment by Dominic-DallOsto** [comment]
I think I correctly wrote a SPARQL query [here](https://query.wikidata.org/#select%20%3Fsuperclass%20%3FsuperclassLabel%20where%20%7B%20%0A%20%20wd%3AQ838948%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%23%20%20%20wd%3AQ30070318%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ686822%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ17928402%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ571%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ3331189%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ47461344%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ7725634%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1980247%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ2334719%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ40056%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ23927052%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%23%20%20%20wd%3AQ30070414%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ49848%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070439%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ13433827%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%23%20%20%20wd%3AQ17329259%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ11424%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ7216866%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%23%20%20%20wd%3AQ30070550%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070565%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ178651%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ13442814%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ133492%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070590%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ87167%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ4006%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ5707594%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ253623%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ24634210%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ604733%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1555508%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ10870555%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ820655%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1266946%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ15416%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070675%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ36774%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%2Cde%2Cfr%2Cpt%2Ccs%2Czh%22.%20%7D%0A%7D) which takes all the types from [the translator](https://github.com/diegodlh/zotero-cita/blob/master/translators/Wikidata%20JSON.js#L46-85) and tries to find their common superclasses. Unfortunately the only one is [entity](https://www.wikidata.org/wiki/Q35120), which is even less restrictive than work. I think the issue is that things like [video recording](https://www.wikidata.org/wiki/Q30070675) aren't subclasses of work.

Alternatively, can we run the untyped query with no type in it at all? Then there shouldn't be a problem with openrefine and once #52 is resolved it should be easy for users to disambiguate anyway.

**Comment by Dominic-DallOsto** [comment]
I just tried the second option and it works nicely.

**Comment by diegodlh** [comment]
Great query! In [this](https://query.wikidata.org/#select%20%3Fsuperclass%20%3FsuperclassLabel%20where%20%7B%20%0A%20%20wd%3AQ838948%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ3302947%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ686822%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ17928402%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ571%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ3331189%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ47461344%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ7725634%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1980247%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ2334719%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ40056%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ23927052%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1580166%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ49848%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070439%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ13433827%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ13433827%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ11424%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ7216866%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20%23wd%3AQ545861%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20%23wd%3AQ30070565%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ178651%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ13442814%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ133492%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ30070590%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ87167%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ4006%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ5707594%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ253623%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ24634210%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ604733%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1555508%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ10870555%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ820655%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ1266946%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ15416%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20%23wd%3AQ30070675%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20wd%3AQ36774%20%20wdt%3AP279%2a%20%3Fsuperclass%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%2Cde%2Cfr%2Cpt%2Ccs%2Czh%22.%20%7D%0A%7D) query, derived from yours, I changed the redirects for the items they redirect to. Only three classes (commented out) do not have `work` as superclass: legal hearing (Q545861), instant message (Q30070565), video recording (Q30070675).

A `work` is decribed as a "physical or virtual object made by humans". I wonder whether _instant message_ and _video recording_ have not been made subclasses of `work` because they may be made by non-humans as well. But given that _email_ (Q30070439) and _audio recording_ (Q3302947) do have `work` as superclass, we may argue in Wikidata that _instant message_ and _video recording_ should too. I wonder whether we could make a similar point between _legal hearing_ (Q545861) and _interview_ (Q178651) or _presentation_ (Q604733).

Anyway, that wouldn't take us any lower in the hierarchy than `work`.

> Alternatively, can we run the untyped query with no type in it at all? Then there shouldn't be a problem with openrefine and once #52 is resolved it should be easy for users to disambiguate anyway.

I think that every time we deal with the `reconcile` function we should consider the pros and cons of being too strict or too flexible. As pointed out in #101:

> there seem to be too opposing tensions in play here: being too stringent about item matching, which may result in users creating duplicates in Wikidata, and being too flexible about it, which may result in Cita assigning wrong QIDs to items (what happened in your bug report). Being strict for exact matches, and leaving room for flexible matching as partial matches (i.e., suggestions) may be a good middle point.

I think your suggestion may be a good one. Probably it never occurred to me that running an unrestricted query would take longer than running a restricted one! Let's go that way, but make sure we continue treating untyped matches as partial matches.

**Comment by Dominic-DallOsto** [comment]
Just did a proper test with the same setup, running each twice:

* `type: creative_work` - 6.3 s and 6.3 s
* no type - 6.3 s and 7.3 s

So it seems the measurements are a bit noisy, but it's not making much of a difference. From looking at openrefine it seems the type filtering happens after they search for the title, so not having a type shouldn't slow down the query...

**Comment by diegodlh** [comment]
> I benchmarked it, getting QIDs for all 43 items in #141. It took 9.3 s to find exact matches for 29 of these items. So very roughly it doesn't seem not specifying a type is making the reconciliation query super slow.

Now that you mention this, given that:
1. a batch reconciliation will use `reconcile` with `options.partial = false` (see #90), 
2. untyped-query results will be [forced](https://github.com/diegodlh/zotero-cita/blob/d1499863618218d5398a4d1831d175facd873087/src/wikidata.js#L190) to non-exact matches, and
3. non-exact matches will be ignored if `options.partial === false`.

What do you think about not doing the untyped queries at all if `options.partial === false`?

**Comment by Dominic-DallOsto** [comment]
> I think your suggestion may be a good one. Probably it never occurred to me that running an unrestricted query would take longer than running a restricted one! Let's go that way, but make sure we continue treating untyped matches as partial matches.

Yeah, if untyped matches are always only partial matches that a user has to check, I think it should be OK to be slightly less restrictive.

**Comment by Dominic-DallOsto** [comment]
> What do you think about not doing the untyped queries at all if options.partial === false?

Ahh yes, that makes sense!

**Comment by diegodlh** [comment]
Cool! If you could add that, it'd be great.

**Comment by Dominic-DallOsto** [comment]
Yep, will do! I had a quick look but it's not trivial because the code at the moment assumes we always have the untyped query results so I'd have to restructure things a little bit. This might take me a couple of days, so I don't know if you'd prefer to merge this to restore QID fetching functionality, then make a new issue to implement this change? Whatever you think.

**Review by diegodlh — APPROVED** [review]

**Comment by diegodlh** [comment]
Sure, sounds reasonable. I'll create a separate issue now. Thank you!!

**Pull request merged**
