### PR TITLE
Right click on items to add them as citations to other item

### LINKED ISSUE #39: Right click on items to add them as citations to other item
Include "Add as citation(s) to..." as an action in the right-click menu in the item tree.

This would be a shortcut to:
1. add items selected as citation target item of another item in the library
2. create link between citation target item created and item selected

### PR DESCRIPTION
**Pull request by Futur3r**
This PR fixes #39.

But I have trouble understanding how to create a citation.
I got kind stuck with this error message :
`JavaScript error: chrome://cita/content/main.js, line 8471: ReferenceError: sourceItem is not defined`

### CODE REVIEW

**Review by Dominic-DallOsto — COMMENTED** [review]
Thanks for taking a look at this! So far looks good and almost runs for me, just I think you might have swapped the source and target items around? I left a few comments.

I'm not sure about 5. yet...

A couple of general things
* Not sure why you deleted `citation.js`? It's needed for this right?
* can you remove your .vscode from the commit, and add .vscode/ to the `.gitignore`, then it won't get accidentally added to the repo?

**Comment by Dominic-DallOsto** [comment]
Ok, thanks for the update! I modified it a bit to also handle multiple source items at once. And to do the linking to a related item automatically when creating the citations.

On my end it seems to work all good now - is it also good for you?

**Review by Dominic-DallOsto — APPROVED** [review]

**Comment by Dominic-DallOsto** [comment]
Also, out of interest, did you get the vscode debugger to attach to Zotero successfully? I just saw it in your launch.json file.

**Comment by Futur3r** [comment]
All good !! Works fine.

For the debugger, no, I tried a lot without any success.

**Pull request merged**
